YokomaMiso/HougekiShoujo

Assets/Resource/Camera/CameraMove.cs, Assets/Resource/Player/PlayerAsset/PlayerAim.cs, Assets/Resource/Player/PlayerAsset/PlayerMove.cs, Assets/Resource/Player/PlayerAsset/PlayerRecoil.cs, Assets/Resource/Player/PlayerAsset/PlayerReload.cs, Assets/Resource/Player/Shell/Explosion/ExplosionBehavior.cs, Assets/Resource/Player/Shell/Projectile/CanonProjectileBehavior.cs, Assets/Resource/Player/Shell/Projectile/MortarProjectileBehavior.cs, Assets/Resource/System/TimeManager.cs
TimeManager.GetDeltaTime()を呼び出すことでスローや時間停止などが出来るように変更
=> Update: TimeManager内のUpdate関数を削除

Assets/Resource/System/EditorExtend.meta, Assets/Resource/System/EditorExtend/TagAttribute.cs, Assets/Resource/System/EditorExtend/TagAttribute.cs.meta
属性欄に**Tag**と入力すればインスペクタビューからプルダウンでプロジェクト内に存在するタグを選択できるようになります
=> TagAttributeの追加

Assets/Resource/Camera/CameraMove.cs, Assets/Resource/Player/PlayerAsset/Player.cs, Assets/Resource/Player/PlayerAsset/PlayerAim.cs, Assets/Resource/Player/Shell/Shell.cs, Assets/Resource/Player/Shell/ShellData.asset, Assets/Resource/Player/Shell/ShellData2.asset, Assets/Resource/Player/Shell/ShellData3.asset, Assets/Scenes/IngameScene.unity
Update: ShellDataに格納する変数を更新
Update: エイム時の挙動を更新
Update: インゲームのカメラをOrthoGraphicに変更
=> Update: ShellDataとエイム時の挙動を更新

Assets/Resource/Player/PlayerAsset/CharaSprite/AnimData.meta, Assets/Resource/Player/PlayerAsset/CharaSprite/AnimData/TestAnimData.asset, Assets/Resource/Player/PlayerAsset/CharaSprite/AnimData/TestAnimData.asset.meta, Assets/Resource/Player/PlayerAsset/CharaSprite/CharacterAnimData.cs, Assets/Resource/Player/PlayerAsset/CharaSprite/CharacterAnimData.cs.meta, Assets/Resource/Player/PlayerAsset/PlayerAim.cs, Assets/Resource/Player/PlayerAsset/PlayerData.cs, Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character1.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character2.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character3.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/TestPlayerData.asset, Assets/Resource/Player/PlayerAsset/PlayerImage.cs, Assets/Resource/Player/SubWeapon/BuffEffectPrefab.prefab
Add: アニメーションデータのScriptableObjectを追加
Fix: Blast使用時、自爆してしまうバグの修正
=> Add: アニメーションデータのScriptableObjectを追加

Assets/Scenes/TitleScene.unity
https://github.com/YokomaMiso/HougekiShoujo/commit/3c5dd34eb6ad2dff3a44d5eeda0b527c69ae84b5
ないし
https://github.com/YokomaMiso/HougekiShoujo/pull/42
で発生したコンフリクト解決時にタイトルシーンのデータが一部欠損したため修正
=> Titlesceneの修正

Assets/Resource/Player/PlayerAsset/Player.cs, Assets/Resource/UI/InGameCanvas/DisplayInGameTimer.cs, Assets/Resource/UI/InGameCanvas/DisplayInGameTimer.cs.meta, Assets/Resource/UI/InGameCanvas/DisplayRound.cs, Assets/Resource/UI/InGameCanvas/DisplayRound.cs.meta, Assets/Resource/UI/InGameCanvas/InGameCanvas.prefab, Assets/Resource/UI/InGameCanvas/InGameStartAndEndText.cs, Assets/Resource/UI/roomCanvas/RoomCanvasBehavior.cs, ProjectSettings/InputManager.asset
Add: キャラアイコン、ラウンド数、タイマーなどを実装
Add: RoomSceneでOptionを呼び出す機能を追加
=> Add: キャラアイコン、ラウンド数、タイマーなどを実装

Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character1.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character2.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/PD_Character3.asset, Assets/Resource/Player/PlayerAsset/PlayerDatas/TestPlayerData.asset, Assets/Resource/Shader.meta, Assets/Resource/Shader/OutLine.shader, Assets/Resource/Shader/OutLine.shader.meta, Assets/Resource/Shader/OutLineMat.mat, Assets/Resource/Shader/OutLineMat.mat.meta
=> Add:OutLine追加しました

Assets/Resource/Shader/OutLine.shader, Assets/Resource/Shader/OutLineMat.mat
=> Updata:輪郭線アップデート

Assets/Resource/System/GameManager.cs, Assets/Resource/System/Network/Data/MachingRoomData.cs, Assets/Resource/System/Network/OSCManager.cs, Assets/Resource/System/RoomManager.cs, Assets/Resource/UI/InGameCanvas/DisplayCharaIcon.cs, Assets/Resource/UI/roomCanvas/PlayerBannerBehavior.cs, Assets/Resource/UI/roomCanvas/RoomCanvasBehavior.cs, ProjectSettings/ProjectSettings.asset
This reverts commit 5b9fd8cff5b1b595f0168a5621b58d08a4604e63.
=> Revert "Fix: 送受信する配列のバグ修正"

Assets/Resource/System/Network/Data/ResponseServerData.cs, Assets/Resource/System/Network/OSCManager.cs
=> ハンドシェイクデータの更新

Assets/Resource/System/Network/Data/AllGameData.cs, Assets/Resource/System/Network/Data/AllGameData.cs.meta, Assets/Resource/System/Network/Data/IngameData.cs, Assets/Resource/System/Network/OSCManager.cs, Assets/Resource/System/RoomManager.cs
=> インゲームへの接続処理完成

Assets/Resource/System/RoomManager.cs, Assets/Resource/UI/InGameCanvas/DisplayCharaIcon.cs
Fix: READY中にキャラ変更できてしまうバグの修正
Add: 死亡しているプレイヤーのアイコンの表示を変更する機能追加
=> Fix: READY中にキャラ変更できてしまうバグの修正

Assets/Resource/Player/ScriptableDatas/PlayerDatas/PD_KonoeTsukasa.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_Acceleration.asset, Assets/Resource/Player/SubWeapon/Blink/Blink.cs, Assets/Resource/Stage/Stage1.prefab
=> Fix: ブリンクのバグ修正

Assets/Resource/Player/PlayerAsset/Player.cs, Assets/Resource/Player/PlayerAsset/PlayerAim.cs, Assets/Resource/System/GameManager.cs, Assets/Resource/UI/InGameCanvas/DisplayCharaIcon.cs
Add: ラウンドシステムの追加
Fix: 次のラウンドで復活しないバグの修正
Fix: 当たり判定が復活しないバグの修正
Fix: ラウンドのカウントのバグを修正
Update: キャラアイコンの演出を初回のみに変更
=> Add: ラウンドシステムの追加

Assets/Resource/Player/PlayerAsset/Player.cs
=> fix:チーム別で色を変更してないのバグを修正した

Assets/Resource/Shader/MiniMap/MiniMapC.cs
=> Fix:コンパイルエラー修復

Assets/Resource/Shader/MiniMap/MiniMap.shader, Assets/Resource/Shader/MiniMap/MiniMapC.cs
Fix:OtherPlayerのファイナルバージョンと確信しています
=> Fix:OtherPlayerのファイナルバージョンと確信しています

Assets/Resource/Player/SubWeapon/Bomb/SlimeBomb/Explosion_Slime.prefab, Assets/Resource/Player/SubWeapon/Bomb/SlimeBomb/SlimeBombPrefab.prefab, Assets/Resource/System/GameManager.cs
Update: スライム爆弾の微修正
Update: ２ラウンド以降のタイマーを修正
=> Update: スライム爆弾とラウンドタイマーの修正

Assets/Resource/Shader/FastChat/FastChatC.cs, Assets/Resource/Shader/FastChat/FastChatM.mat
Fix:FastChat一部の色を変わってないのバグを修正しました
=> Fix:FastChat一部の色を変わってないのバグを修正しました

Assets/Resource/Player/ScriptableDatas/ShellDatas/SD_NanamiProjectile.asset, Assets/Resource/UI/ResultCanvas/ResultCanvasBehavior.cs, Assets/Scenes/TitleScene.unity
・七海のスキルアイコンを仮挿し
・リザルトシーンで決定ボタンを押せるまでの時間を短縮
・タイトルシーンで無効になっているボタンの色を変更
=> Update: 細かな更新

Assets/Resource/System/GameManager.cs, Assets/Resource/UI/LogoSplashCanvas/LogoSplashCanvasBehavior.cs, Assets/Scenes/TitleScene.unity
・ゲーム終了後にも一瞬だけスコアボードを開けてしまう不具合修正
・LogoSplashの後半でアルファ値を下げる処理を削除
・タイトル画面にステージを設置
=> Update: 細かな調整

Assets/Resource/Stage/StageData.cs, Assets/Resource/System/GameManager.cs, Assets/Resource/System/Network/Data/MachingRoomData.cs, Assets/Resource/System/RoomManager.cs
=> Add: ステージをランダムで決定する機能を追加

Assets/Resource/Player/SubWeapon/Blink/Blink.cs, Assets/Resource/Stage/StageData/Stage1Data.asset, Assets/Resource/Stage/StageData/Stage3Data.asset, Assets/Resource/Stage/SuddenDeathArea.cs, Assets/Resource/Stage/SuddenDeathArea.cs.meta, Assets/Resource/Stage/SuddenDeathArea.mat, Assets/Resource/Stage/SuddenDeathArea.mat.meta, Assets/Resource/Stage/SuddenDeathArea.prefab, Assets/Resource/Stage/SuddenDeathArea.prefab.meta, Assets/Resource/Stage/SuddenDeathArea.shadergraph, Assets/Resource/Stage/SuddenDeathArea.shadergraph.meta, Assets/Resource/Stage/SuddenDeathSphere.cs, Assets/Resource/Stage/SuddenDeathSphere.cs.meta, Assets/Resource/System/GameManager.cs, Assets/Resource/System/GameManager.cs.meta, Assets/Resource/System/Managers.prefab
Add: サドンデスエリアの追加
Fix: ブリンクを使用する度にY座標がどんどん上昇してしまう不具合の修正
=> Add: サドンデスエリアの追加

Assets/Resource/UI/TitleCanvas/TitleCanvasBehavior.cs, Assets/Resource/UI/TitleCanvas/TitleCanvasBehavior.cs.meta, Assets/Scenes/TitleScene.unity, UpgradeLog.htm
=> Add: TitleBgmの追加

Assets/Resource/System/Network/Data/OscClientData.cs, Assets/Resource/System/Network/Data/OscClientData.cs.meta, Assets/Resource/System/Network/OSCManager.cs, Assets/Resource/System/RoomManager.cs, Assets/Resource/UI/ConnectionCanvas/ConnectionCanvasBehavior.cs
=> クライアント再接続時のバグ修正

Assets/Resource/System/EditorExtend/ShowFPSGUI.cs, Assets/Resource/System/EditorExtend/ShowFPSGUI.cs.meta
ビルドしたファイルだとどれぐらい出ているか確認したいため追加
=> フレームレート表示機能追加

.github/workflows/build.yml
=> add: googleDriveへのアップロード

Assets/Resource/UI/roomCanvas/roomCanvas.prefab
=> Update: ルームのフォントを変更

Assets/Resource/Stage/Stage4.prefab, Assets/Resource/Stage/Stage4.prefab.meta, Assets/Resource/Stage/StageData/AllStageData.asset, Assets/Resource/Stage/StageData/Stage4Data.asset, Assets/Resource/Stage/StageData/Stage4Data.asset.meta, Assets/test 1.mat, Assets/test 1.mat.meta, Assets/test 2.mat, Assets/test 2.mat.meta, Assets/test 3.mat, Assets/test 3.mat.meta, Assets/test 4.mat, Assets/test 4.mat.meta, Assets/test.mat, Assets/test.mat.meta
縦蛇行の仮ステージを作成。
StageDataに入れて確認してください。
当たり判定に問題あり。
Building　右からあたるとおかしくなる。
Building(1)　上と左からあたるとおかしくなる。
Building(2)　右からあたるとおかしくなる。
Wall_BottomLeft　上と右からあたるとおかしくなる。
Fence　右からあたるとおかしくなる。
Fence(1)　右からあたるとおかしくなる。
VendingMachine (1)　右からあたるとおかしくなる。
Wall_Center　右からあたるとおかしくなる。Car(1)　上と左からあたるとおかしくなる。
Wall_Bottom　上からあたるとおかしくなる。
=> Add:NewStage

Assets/Resource/System/Network/OSCManager.cs
=> update: 使用するポートを動的（50000～）へ変更

Assets/Resource/Player/PlayerAsset/PlayerSubAction.cs, Assets/Resource/Player/ScriptableDatas/SubWeaponData/ED_EMPExplosion.asset, Assets/Resource/Player/SubWeapon/Bomb/BombBehavior.cs, Assets/Resource/Player/SubWeapon/Installation/EMP/EMPExplosionBehavior.cs, Assets/Resource/Player/SubWeapon/Installation/EMP/EMPMine.cs, Assets/Resource/Player/SubWeapon/Installation/EMP/Explosion_EMP.prefab, Assets/Resource/Player/SubWeapon/Installation/EMP/MinePrefab.prefab, Assets/Resource/Player/SubWeapon/Installation/InstallationBehavior.cs, Assets/Resource/Player/SubWeapon/RoundCheckerSubWeapon.cs, Assets/Resource/Player/SubWeapon/RoundCheckerSubWeapon.cs.meta, Assets/Resource/System/SaveManager.cs
Update: EMP、EMP爆発のサイズを大きくし、２個目を設置した時に起爆する仕様に変更
Add: ラウンドが進んだ時に設置物を破棄する仕様を追加
=> Update: EMPの調整とラウンド変更時にサブ武器を破棄する仕様追加

Assets/Resource/System/Network/OSCManager.cs
debug.logがかなり重かったためコメントアウトしています
=> OSCManagerのdebug.log削除

Assets/Resource/System/RoomManager.cs, Assets/Resource/UI/TitleCanvas/TitleButtons.cs
・タイトルでBボタンを押すとExitにカーソルが移動する機能を追加
・メンバー数が同数じゃないとゲーム開始できないように修正
=> Update: 軽微な調整

Assets/Resource/Player/PlayerAsset/PlayerRadioChat.cs, Assets/Resource/Shader/FastChat/FastChatC.cs, Assets/Resource/Shader/FastChat/FastChatS.shader, Assets/Resource/UI/InGameCanvas/TeamChat/CharaSerifBehavior.cs
・ついでにキーボードの１～８を押下時にラジオチャットが出る機能を追加
=> Fix: ラジオチャットの回転の不具合を修正

Assets/Resource/Player/PlayerAsset/PlayerAim.cs, Assets/Resource/Player/PlayerAsset/PlayerMove.cs, Assets/Resource/Shader/FastChat/FastChatC.cs, Assets/Resource/System/InputManager.cs, Assets/Resource/System/Managers.cs, Assets/Resource/UI/GalleryCanvas/Char/CharScrollBar.cs, Assets/Resource/UI/GalleryCanvas/GalleryManager.cs, Assets/Resource/UI/SelectRoomCanvas/SelectRoomCanvasBehavior.cs, Assets/Resource/UI/TitleCanvas/CreditCanvasBehavior.cs, Assets/Resource/UI/TitleCanvas/TitleButtons.cs, Assets/Resource/UI/optionCanvas/OptionCanvasBehavior.cs, Assets/Resource/UI/roomCanvas/RoomCanvasBehavior.cs
GetAxis系の取得可能変数の追加：boolもしくはVector2で取得可能
GetAxisDelayの追加：既存のGetAxis系の第二引数に秒数を指定することでその秒数ごとに入力取得可能
InputSysremのEnableとDisableの追加
=> Update: GetAxis系の新機能、InputSystemの有効無効

Assets/Resource/UI/TitleCanvas/InputName.cs, Assets/Resource/UI/TitleCanvas/TitleButtons.cs, Assets/Resource/UI/roomCanvas/RoomCanvasBehavior.cs
・名前入力処理で仕様通りじゃなかった部分を修正
・タイトルボタンの入力処理を一部修正
・キャラセレクトの入力処理を一部修正
=> Update: 各UIの細かな調整

Assets/Scenes/GalleryScene.unity
Fix:ギャラリーのイベントシステムのInput モジュール修正
=> Fix:ギャラリーのイベントシステムのInput モジュール修正

Assets/Resource/Stage/KyushaMae/Materials/Assets_Map.mat, Assets/Resource/Stage/KyushaMae/Materials/Map1GroundTest3.mat, Assets/Resource/Stage/KyushaMae/Materials/schoolWalls.mat, Assets/Scenes/GalleryScene.unity, Assets/Settings/URP-Performant-Renderer.asset, Assets/Settings/URP-Performant.asset
Fix:影を反映されないのバグとギャラリーのバグを修正しました
=> Fix:影を反映されないのバグとギャラリーのバグを修正しました

Assets/Resource/UI/GalleryCanvas/Char/Character/Data/ChikaneGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/JuliaGalleryCharacterData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/KurumiGalleryCharacterData 1.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/NanamiGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/TsukasaGalleryCharacterData 2.asset, Assets/Scenes/GalleryScene.unity
Fix:ギャラリーのキャラクターイラストが正しくないのバグを修正しました
=> Fix:ギャラリーのキャラクターイラストが正しくないのバグを修正しました

Assets/Resource/Player/ScriptableDatas/ExplosionDatas/ED_KotoCanonExplosion.asset, Assets/Resource/Player/ScriptableDatas/ExplosionDatas/ED_RanBlastExplosion.asset, Assets/Resource/Player/ScriptableDatas/ExplosionDatas/ED_RanBlastExplosion.asset.meta, Assets/Resource/Player/ScriptableDatas/ShellDatas/SD_KotoCanonProjectile.asset, Assets/Resource/Player/ScriptableDatas/ShellDatas/SD_RanProjectile.asset, Assets/Resource/Player/Shell/Projectile/Koto/BackBlastCanonBehavior.cs, Assets/Resource/Player/Shell/Projectile/Ran/RanProjectileBehaviour.cs, Assets/Resource/Shader/MiniMap/MiniMapMaterial.mat
Update: 琴の調整
・メイン爆風範囲1.5→1.0
・飛翔体生存時間0.6→0.75
・バックファイアの生成位置を調整
Update: 蘭の調整
・爆発の挙動を大幅に変更（縦に広がる→横に広がる）
・射撃してから起爆までの時間0.4sec→0.6sec
=> Update: キャラ調整

Assets/Resource/Player/Shell/Projectile/Mirai/MiraiProjectileBehavior.cs, Assets/Resource/Shader/MiniMap/MiniMapMaterial.mat, Assets/Resource/Stage/KyushaMae/KyuushamaeMap_Asset/Floor.fbx.meta, Assets/Resource/Stage/StagePrefab/KyushaMae.prefab, Assets/Resource/UI/SelectRoomCanvas/SelectRoomCanvas.prefab
=> Update: 軽微な修正

Assets/Resource/Player/PlayerAsset/CharaSprite/SpriteSheet/Julia/Reload/Julia_Reload_Right_0.controller, Assets/Resource/Player/ScriptableDatas/ShellDatas/SD_JuliaCanonProjectile.asset, Assets/Resource/Player/Shell/Projectile/Chikane/ChikaneBlastProjectileBehavior.cs
・朱里亜
　弾速…10→12
　生存時間…0.75sec→0.625sec
　リロード…2.0sec→1.5sec
・千鉄
　ディレイ…0.6sec→0.4sec
=> Update: キャラの調整

Assets/Resource/Shader/MiniMap/MiniMapC.cs
=> Fix:ミニマップのデバッグ用機能を修正しました

Assets/Resource/Player/PlayerAsset/CharaSprite/SpriteSheet/Ran/Reload/Ran_Reload_Right_0.controller, Assets/Resource/Player/ScriptableDatas/ShellDatas/SD_RanProjectile.asset
=> Update: 蘭の調整

Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_Acceleration.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_BlueCoral.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_PileBunker.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_SpiderBomb.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_TapiocaBomb.asset, Assets/Resource/Player/ScriptableDatas/SubWeaponData/SW_TeenSpirit.asset, Assets/Resource/Player/SubWeapon/Bomb/SpiderBomb/SpiderExplosionBehavior.cs, Assets/Resource/Player/SubWeapon/Installation/BlueCoral/BlueCoralBehavior.cs, Assets/Resource/Player/SubWeapon/Installation/PileBunker/PileBunkerBehavior.cs
アクセラ…持続時間を5sec→3sec
ブルーコーラル…持続時間を8sec→5sec
地ならし…持続時間を8sec→1secに、減少量を0.65→0.0に変更
蜘蛛爆弾…持続時間を5sec→8secに、減少量を0.7→0.5に変更
=> Update: サブ武器の調整

Assets/Resource/UI/GalleryCanvas/Char/Character/Data/ChikaneGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/JuliaGalleryCharacterData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/KotoGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/KurumiGalleryCharacterData 1.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/NanamiGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/RanGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/SaraGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/TsukasaGalleryCharacterData 2.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/GalleryCharData.cs, Assets/Resource/UI/GalleryCanvas/Char/Character/Prefab/VoicePrefab.prefab, Assets/Resource/UI/GalleryCanvas/Char/MainViewPort.cs
=> Updata:キャラクターボイスのテキストを追加しました

Assets/Resource/UI/GalleryCanvas/Char/Character/Data/ChikaneGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/KotoGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/KurumiGalleryCharacterData 1.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/NanamiGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/RanGalleryData.asset, Assets/Resource/UI/GalleryCanvas/Char/Character/Data/SaraGalleryData.asset
Updata:ギャラリーにくるみ、千鉄、七海、沙羅、琴、蘭のボイスを追加しました
=> Updata:ギャラリーにくるみ、千鉄、七海、沙羅、琴、蘭のボイスを追加しました

Assets/Resources/Stage/StagePrefab/JunkYard.prefab, Assets/Resources/Stage/StagePrefab/KyushaMae.prefab, Assets/Resources/Stage/StagePrefab/Stage5.prefab, Assets/Resources/Stage/StagePrefab/Stage6.prefab
=> Add:竹が生えてこないエリアの追加

Assets/Resources/System/InputManager.cs, Assets/Resources/System/PlayerController.inputactions, Assets/Resources/UI/GalleryCanvas/Char/MainViewPort.cs
=> Updata:Westボタンを追加しました
